import Head from 'next/head'
import sass from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={sass.home}>
      <Head>
        <title>Udevs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <div className={sass.left}> 
           
        </div>
        <div className={sass.right}> </div>
      </header>
    
    </div>
  )
}


